#!/usr/bin/env python3
"""
Decision Index Manager

Creates and refreshes `shared/decisions/decision-index.md` from ADR files.

Usage:
    python3 decision_index.py init [--root <project_root>]
    python3 decision_index.py refresh [--root <project_root>]

Exit codes:
    0 = Success
    1 = Runtime error
    2 = Argument error
"""

from __future__ import annotations

import argparse
import re
import sys
from dataclasses import dataclass
from datetime import datetime
from pathlib import Path
from typing import Any

try:
    import yaml
except ImportError:
    yaml = None


@dataclass
class AdrEntry:
    adr_id: str
    status: str
    date: str
    title: str
    rel_path: str
    order: int


def _parse_front_matter(md_text: str) -> dict[str, Any]:
    """Parse YAML front matter from markdown text."""
    if not md_text.startswith("---"):
        return {}
    parts = md_text.split("\n---", 2)
    if len(parts) < 2:
        return {}
    block = parts[0].lstrip("-").strip()
    if yaml is None:
        # Fallback parser for simple "key: value" front matter when PyYAML
        # is unavailable. Nested structures are intentionally ignored.
        parsed: dict[str, Any] = {}
        for raw in block.splitlines():
            line = raw.strip()
            if not line or line.startswith("#"):
                continue
            m = re.match(r"^([A-Za-z0-9_]+)\s*:\s*(.+)$", line)
            if not m:
                continue
            key, value = m.group(1), m.group(2).strip()
            if " #" in value:
                value = value.split(" #", 1)[0].rstrip()
            if (value.startswith('"') and value.endswith('"')) or (value.startswith("'") and value.endswith("'")):
                value = value[1:-1]
            parsed[key] = value
        return parsed
    try:
        parsed = yaml.safe_load(block)
        if isinstance(parsed, dict):
            return parsed
    except Exception:
        pass

    # Secondary fallback for malformed YAML / partial metadata
    fallback: dict[str, Any] = {}
    for raw in block.splitlines():
        line = raw.strip()
        m = re.match(r"^([A-Za-z0-9_]+)\s*:\s*(.+)$", line)
        if not m:
            continue
        value = m.group(2).strip()
        if " #" in value:
            value = value.split(" #", 1)[0].rstrip()
        fallback[m.group(1)] = value.strip("\"'")
    return fallback


def _sanitize_md_cell(value: str) -> str:
    """Escape markdown table-breaking characters."""
    return value.replace("|", "\\|").replace("\n", " ").strip()


def _extract_title(md_text: str, fallback: str) -> str:
    """Extract first H1 title from markdown."""
    for line in md_text.splitlines():
        if line.startswith("# "):
            title = line[2:].strip()
            # Normalize "ADR-001: something" -> "something"
            m = re.match(r"ADR-\d+\s*:\s*(.+)", title, flags=re.IGNORECASE)
            if m:
                return m.group(1).strip()
            return title
    return fallback


def _parse_adr_entry(path: Path, project_root: Path) -> AdrEntry | None:
    """Parse one ADR file into an index entry."""
    m = re.match(r"(ADR-(\d+))-(.+)\.md$", path.name)
    if not m:
        return None
    adr_id = m.group(1)
    order = int(m.group(2))

    text = path.read_text(encoding="utf-8")
    fm = _parse_front_matter(text)

    status = str(fm.get("status", "proposed")).strip() or "proposed"
    date = str(fm.get("date", "")).strip()
    if not date:
        date = datetime.fromtimestamp(path.stat().st_mtime).strftime("%Y-%m-%d")

    default_title = m.group(3).replace("-", " ").strip().title()
    title = str(fm.get("title", "")).strip() or _extract_title(text, default_title)

    rel_path = path.relative_to(project_root).as_posix()
    return AdrEntry(
        adr_id=adr_id,
        status=status,
        date=date,
        title=title,
        rel_path=rel_path,
        order=order,
    )


def collect_adrs(project_root: Path) -> list[AdrEntry]:
    """Collect all ADR entries from shared/decisions."""
    decisions_dir = project_root / "shared" / "decisions"
    if not decisions_dir.exists():
        return []
    entries: list[AdrEntry] = []
    for path in sorted(decisions_dir.glob("ADR-*.md")):
        entry = _parse_adr_entry(path, project_root)
        if entry:
            entries.append(entry)
    entries.sort(key=lambda e: e.order)
    return entries


def render_index(entries: list[AdrEntry]) -> str:
    """Render decision-index markdown."""
    today = datetime.now().strftime("%Y-%m-%d")
    lines: list[str] = []
    lines.append("# Decision Index")
    lines.append("")
    lines.append("> Auto-generated by `python3 sdd-templates/tools/decision_index.py refresh`.")
    lines.append(f"> Updated: {today}")
    lines.append("")
    lines.append("| ADR ID | Status | Date | Title | File |")
    lines.append("|--------|--------|------|-------|------|")
    if not entries:
        lines.append("| - | - | - | No ADR files yet | - |")
    else:
        for e in entries:
            adr_id = _sanitize_md_cell(e.adr_id)
            status = _sanitize_md_cell(e.status)
            date = _sanitize_md_cell(e.date)
            title = _sanitize_md_cell(e.title)
            rel_path = _sanitize_md_cell(e.rel_path)
            lines.append(f"| `{adr_id}` | {status} | {date} | {title} | `{rel_path}` |")
    lines.append("")
    return "\n".join(lines)


def init_index(project_root: Path) -> tuple[Path, int]:
    """Initialize shared/decisions and write decision-index.md."""
    decisions_dir = project_root / "shared" / "decisions"
    decisions_dir.mkdir(parents=True, exist_ok=True)
    return refresh_index(project_root)


def refresh_index(project_root: Path) -> tuple[Path, int]:
    """Refresh decision-index from existing ADR files."""
    decisions_dir = project_root / "shared" / "decisions"
    decisions_dir.mkdir(parents=True, exist_ok=True)
    index_path = decisions_dir / "decision-index.md"
    entries = collect_adrs(project_root)
    index_path.write_text(render_index(entries), encoding="utf-8")
    return index_path, len(entries)


def _run_self_tests() -> None:
    """Run script self-tests."""
    import tempfile

    print("Running self-tests...")

    with tempfile.TemporaryDirectory() as tmpdir:
        root = Path(tmpdir)

        # Test 1: init creates decision-index
        index_path, count = init_index(root)
        assert index_path.exists(), "decision-index.md should be created"
        assert count == 0, f"expected 0 ADR entries, got {count}"
        print("  Test 1 passed: init creates empty index")

        decisions_dir = root / "shared" / "decisions"
        adr2 = decisions_dir / "ADR-002-api-versioning.md"
        adr2.write_text(
            "---\n"
            "status: accepted\n"
            "date: 2026-02-08\n"
            "title: API versioning strategy\n"
            "---\n\n"
            "# ADR-002: API versioning strategy\n",
            encoding="utf-8",
        )
        adr1 = decisions_dir / "ADR-001-domain-boundary.md"
        adr1.write_text(
            "---\n"
            "status: proposed\n"
            "date: 2026-02-07\n"
            "title: Domain boundary baseline\n"
            "---\n\n"
            "# ADR-001: Domain boundary baseline\n",
            encoding="utf-8",
        )

        # Test 2: refresh picks up ADR files and sorts by numeric id
        index_path, count = refresh_index(root)
        content = index_path.read_text(encoding="utf-8")
        assert count == 2, f"expected 2 ADR entries, got {count}"
        assert content.find("`ADR-001`") < content.find("`ADR-002`"), "ADR sort order incorrect"
        print("  Test 2 passed: refresh sorts ADRs by numeric order")

        # Test 3: metadata rendered
        assert "accepted" in content, "status metadata not rendered"
        assert "API versioning strategy" in content, "title metadata not rendered"
        print("  Test 3 passed: metadata rendering")

    print("All 3 self-tests passed.")
    sys.exit(0)


def main() -> None:
    parser = argparse.ArgumentParser(description="Manage shared ADR decision index.")
    sub = parser.add_subparsers(dest="command")

    p_init = sub.add_parser("init", help="Initialize decision index")
    p_init.add_argument("--root", default=".", help="Project root path")

    p_refresh = sub.add_parser("refresh", help="Refresh decision index from ADR files")
    p_refresh.add_argument("--root", default=".", help="Project root path")

    parser.add_argument("--test", action="store_true", help="Run self-tests")
    args = parser.parse_args()

    if args.test:
        _run_self_tests()
        return

    if not args.command:
        parser.error("the following arguments are required: command")

    project_root = Path(getattr(args, "root", ".")).resolve()

    try:
        if args.command == "init":
            index_path, count = init_index(project_root)
            print(f"PASS: initialized {index_path} (ADR entries: {count})")
        elif args.command == "refresh":
            index_path, count = refresh_index(project_root)
            print(f"PASS: refreshed {index_path} (ADR entries: {count})")
        else:
            print(f"FAIL: unknown command: {args.command}")
            sys.exit(2)
    except Exception as exc:  # pragma: no cover - defensive runtime guard
        print(f"FAIL: {exc}")
        sys.exit(1)

    sys.exit(0)


if __name__ == "__main__":
    main()
