#!/usr/bin/env python3
"""build_basic_design_html.py — basic_design.md → HTML 変換 (Phase F WI-VALF01-011 / 改善要望-10)

Tecnos-STRIDE 本体の helper script。Plugin (cowork-plugin/) には同梱せず、
Tecnos-STRIDE 本体の clone 済み環境で `cowork-plugin/commands/stride-export-html.md`
から呼び出される (DR-103: Plugin 配布物最小化のための本体側配置)。

入力: specs/<feature>/basic_design.md (canonical YAML + 説明文の二段構造)
出力: specs/<feature>/exports/basic_design_<feature>.html (顧客レビュー向け HTML)

Usage:
    python3 scripts/build_basic_design_html.py specs/val_f01/basic_design.md
    python3 scripts/build_basic_design_html.py specs/val_f01/basic_design.md \\
            --output specs/val_f01/exports/basic_design_val_f01.html

Reference: specs/val_f01/spec.md US-FEATVALF01-011 / AC-US-FEATVALF01-011-01
          specs/val_f01/plan.md CT-CLI-06 / TS-CON-11 / TS-INT-03
"""
from __future__ import annotations

import argparse
import sys
from pathlib import Path

try:
    import markdown  # type: ignore
except ImportError:
    print(
        "ERROR: 'markdown' module not installed. Run: pip install markdown",
        file=sys.stderr,
    )
    sys.exit(2)


HTML_TEMPLATE = """<!DOCTYPE html>
<html lang="ja">
<head>
<meta charset="utf-8">
<title>{title}</title>
<style>
  body {{ font-family: -apple-system, "Segoe UI", "Hiragino Sans", "Yu Gothic", sans-serif;
          max-width: 980px; margin: 2em auto; padding: 0 1em; line-height: 1.6; color: #222; }}
  h1, h2, h3, h4 {{ border-bottom: 1px solid #eaecef; padding-bottom: 0.3em; }}
  h1 {{ color: #0366d6; }}
  pre {{ background: #f6f8fa; padding: 1em; overflow: auto; border-radius: 6px; font-size: 0.92em; }}
  code {{ background: #f6f8fa; padding: 0.2em 0.4em; border-radius: 3px; font-size: 0.9em; }}
  table {{ border-collapse: collapse; width: 100%; }}
  th, td {{ border: 1px solid #d0d7de; padding: 0.4em 0.7em; }}
  th {{ background: #f6f8fa; }}
  blockquote {{ border-left: 4px solid #d0d7de; padding-left: 1em; color: #57606a; margin-left: 0; }}
  .meta {{ color: #57606a; font-size: 0.9em; margin-bottom: 1em; }}
</style>
</head>
<body>
<div class="meta">
  Generated by <code>scripts/build_basic_design_html.py</code> (Phase F WI-VALF01-011)<br>
  Source: <code>{source}</code>
</div>
{body}
</body>
</html>
"""


def build_html(source_md: Path, title: str | None = None) -> str:
    """Convert a basic_design.md (canonical YAML + Markdown sections) to a self-contained HTML."""
    if not source_md.is_file():
        raise FileNotFoundError(f"basic_design.md not found: {source_md}")

    text = source_md.read_text(encoding="utf-8")

    # Markdown-it like rendering — Python `markdown` package handles fenced code (yaml/python) +
    # tables + admonitions out of the box. The canonical YAML block (#0) is rendered as
    # a fenced code block as-is, which is what we want for human review.
    md = markdown.Markdown(
        extensions=[
            "extra",         # tables, fenced_code, footnotes, attr_list, def_list, abbr
            "toc",           # auto TOC anchors
            "sane_lists",    # consistent list parsing
            "admonition",    # > [!NOTE] style
        ]
    )
    body_html = md.convert(text)

    if title is None:
        # Try to extract first H1 or fall back to file name
        for line in text.splitlines():
            stripped = line.strip()
            if stripped.startswith("# ") and not stripped.startswith("# 0"):
                title = stripped[2:].strip()
                break
        if title is None:
            title = source_md.stem

    return HTML_TEMPLATE.format(title=title, source=source_md, body=body_html)


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("source", type=Path, help="Path to basic_design.md")
    parser.add_argument(
        "--output",
        type=Path,
        default=None,
        help="Output HTML path (default: <source_dir>/exports/basic_design_<feature>.html)",
    )
    parser.add_argument("--title", type=str, default=None, help="HTML <title> override")
    args = parser.parse_args(argv)

    source: Path = args.source
    if not source.is_file():
        print(f"ERROR: source file not found: {source}", file=sys.stderr)
        return 1

    output: Path
    if args.output is not None:
        output = args.output
    else:
        # Default: specs/<feature>/exports/basic_design_<feature>.html
        feature_dir = source.parent
        feature_name = feature_dir.name
        output = feature_dir / "exports" / f"basic_design_{feature_name}.html"

    output.parent.mkdir(parents=True, exist_ok=True)
    html = build_html(source, title=args.title)
    output.write_text(html, encoding="utf-8")
    print(f"✅ HTML generated: {output} ({len(html)} bytes)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
